name: S3 Deploy
on:
  push:
    branches:
      - master

jobs:

  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Cache node modules
        uses: actions/checkout@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:unit

      - name: Build
        run: npm run build
        
  continuous-deployment:
   runs-on: ubuntu-latest
   needs: [continuous-integration]
   if: github.ref == 'refs/heads/main'
   steps:

     - name: Install AWS CLI
       uses: unfor19/install-aws-cli-action@v1
       with:
          version: 1
       env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
     - name: Deploy
       env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       run: |
          aws s3 cp \
            --recursive \
            --region ap-southeast-1 \
            [dist folder] s3://[s3 bucket name]

      
